#!/usr/bin/env bash
set -euo pipefail

ENV_NAME=${1:?Usage: ./configure.sh <dev|stage|prod>}

# Validate environment name
case "${ENV_NAME}" in
  dev|stage|prod)
    ;; # ok
  *)
    echo "Error: environment must be one of: dev, stage, prod (got: '${ENV_NAME}')" >&2
    exit 1
    ;;
esac

# Derive hosts — prod uses bare domains, dev/stage use prefixed subdomains
case "${ENV_NAME}" in
  prod)
    WS_HOST="ws.rgem.io"
    API_HOST="api.rgem.io"
    ;;
  *)
    WS_HOST="ws-${ENV_NAME}.rgem.io"
    API_HOST="api-${ENV_NAME}.rgem.io"
    ;;
esac

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# 1. Root .env — canonical source of truth for the stamped environment
cat > "${SCRIPT_DIR}/.env" <<EOF
RGEM_ENV=${ENV_NAME}
RGEM_WS_HOST=${WS_HOST}
RGEM_API_HOST=${API_HOST}
EOF

# 2. app/.env — consumed by Vite at dev/build time
cat > "${SCRIPT_DIR}/app/.env" <<EOF
VITE_WS_URL=wss://${WS_HOST}
VITE_API_URL=https://${API_HOST}
EOF

# 3. device/core/config.h — consumed by Arduino build
cat > "${SCRIPT_DIR}/device/core/config.h" <<EOF
// Generated by configure.sh — do not commit.
#ifndef CONFIG_H
#define CONFIG_H
#define WEBSOCKET_HOST "${WS_HOST}"
#define WEBSOCKET_PORT 443
#endif
EOF

echo "Configured for '${ENV_NAME}':"
echo "  .env"
echo "  app/.env"
echo "  device/core/config.h"
