AWSTemplateFormatVersion: "2010-09-09"

# NOTE. Enables SAM shorthand for any AWS::Serverless::* resources
Transform: AWS::Serverless-2016-10-31
Description: >
  rgempad-backend

  SAM Template for rgempad-backend that has the DynamoDB table and Lambda
  functions needed to demonstrate the Websocket protocol on API Gateway.

Resources:

# State ######
  ConnectionsTable:
    # Holds the connection identifiers for each connected client
    # NOTE: By default SAM uses PAY_PER_REQUEST billing (on-demand) and enables SSE with an AWS-managed CMK.
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: !Sub "${AWS::StackName}-connections-table"
      PrimaryKey:
        Name: connectionId
        Type: String

  GridStateTable:
    # Holds the 16-bit grid state for each “set”
    # NOTE: By default SAM uses PAY_PER_REQUEST billing (on-demand) and enables SSE with an AWS-managed CMK.
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: !Sub "${AWS::StackName}-grid-state-table"
      PrimaryKey:
        Name: setId
        Type: String

#######
  RGempadBackendApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: RGempadBackendApi
      ProtocolType: WEBSOCKET
      # The route selection expression determines how the API Gateway selects the route to invoke based on the request.
      # In this case, we use the request body to determine the route.
      # The expression "$request.body.type" means that the API Gateway will look for a "type" field in the JSON body of the request to determine which route to invoke.
      RouteSelectionExpression: "$request.body.type"

#######
  ConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref RGempadBackendApi
      RouteKey: $connect
      AuthorizationType: NONE
      OperationName: ConnectRoute
      Target: !Join
        - "/"
        - - "integrations"
          - !Ref ConnectInteg
  ConnectInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref RGempadBackendApi
      Description: Connect Integration
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${OnConnectFunction.Arn}/invocations

#######
  DisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref RGempadBackendApi
      RouteKey: $disconnect
      AuthorizationType: NONE
      OperationName: DisconnectRoute
      Target: !Join
        - "/"
        - - "integrations"
          - !Ref DisconnectInteg
  DisconnectInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref RGempadBackendApi
      Description: Disconnect Integration
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${OnDisconnectFunction.Arn}/invocations

#######
  HelloRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref RGempadBackendApi
      # Note: that the route key is "hello" which means that the API Gateway will look for a "type" field in the JSON body
      # of the request with the value "hello" to invoke this route, per the RouteSelectionExpression.
      # WARNING: Changing the RouteKey will require forcing a new deployment.
      # Td. Learn how to forace a new deployment without having to delete the stack
      RouteKey: hello
      AuthorizationType: NONE
      OperationName: HelloRoute
      Target: !Join
        - "/"
        - - "integrations"
          - !Ref HelloInteg
  HelloInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref RGempadBackendApi
      Description: Hello Integration
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${OnHelloFunction.Arn}/invocations

#######
  ToggleRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref RGempadBackendApi
      RouteKey: toggle
      AuthorizationType: NONE
      OperationName: ToggleRoute
      Target: !Join
        - "/"
        - - "integrations"
          - !Ref ToggleInteg
  ToggleInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref RGempadBackendApi
      Description: Toggle Integration
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${OnToggleFunction.Arn}/invocations

#######
  Deployment:
    Type: AWS::ApiGatewayV2::Deployment
    DependsOn:
      - ConnectRoute
      - DisconnectRoute
      - HelloRoute
      - ToggleRoute
    Properties:
      ApiId: !Ref RGempadBackendApi

#######
  Stage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      StageName: Prod
      Description: Prod Stage
      DeploymentId: !Ref Deployment
      ApiId: !Ref RGempadBackendApi

#######
  OnConnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: onconnect/
      Handler: app.handler
      MemorySize: 256
      Runtime: nodejs20.x
      Environment:
        Variables:
          CONNECTIONS_TABLE: !Ref ConnectionsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ConnectionsTable

  OnConnectPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - RGempadBackendApi
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref OnConnectFunction
      Principal: apigateway.amazonaws.com

#######
  OnDisconnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ondisconnect/
      Handler: app.handler
      MemorySize: 256
      Runtime: nodejs20.x
      Environment:
        Variables:
          CONNECTIONS_TABLE: !Ref ConnectionsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ConnectionsTable

  OnDisconnectPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - RGempadBackendApi
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref OnDisconnectFunction
      Principal: apigateway.amazonaws.com

#######
  OnHelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: onhello/
      Handler: app.handler
      MemorySize: 256
      Runtime: nodejs20.x
      Environment:
        Variables:
          GRID_STATE_TABLE: !Ref GridStateTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref GridStateTable
        - Statement:
          - Effect: Allow
            Action:
              - "execute-api:ManageConnections"
            Resource:
              - !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RGempadBackendApi}/*"

  OnHelloPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - RGempadBackendApi
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref OnHelloFunction
      Principal: apigateway.amazonaws.com

#######
  OnToggleFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ontoggle/
      Handler: app.handler
      MemorySize: 256
      Runtime: nodejs20.x
      Environment:
        Variables:
          CONNECTIONS_TABLE: !Ref ConnectionsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ConnectionsTable
        - Statement:
            - Effect: Allow
              Action:
                - "execute-api:ManageConnections"
              Resource:
                - !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RGempadBackendApi}/*"

  OnTogglePermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - RGempadBackendApi
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref OnToggleFunction
      Principal: apigateway.amazonaws.com

Outputs:
  ConnectionsTableArn:
    Description: "Connections table ARN"
    Value: !GetAtt ConnectionsTable.Arn

  GridStateTableArn:
    Description: "Grid State table ARN"
    Value: !GetAtt GridStateTable.Arn

  OnConnectFunctionArn:
    Description: "OnConnect function ARN"
    Value: !GetAtt OnConnectFunction.Arn

  OnDisconnectFunctionArn:
    Description: "OnDisconnect function ARN"
    Value: !GetAtt OnDisconnectFunction.Arn

  OnHelloFunctionArn:
    Description: "OnHello function ARN"
    Value: !GetAtt OnHelloFunction.Arn

  OnToggleFunctionArn:
    Description: "OnToggle function ARN"
    Value: !GetAtt OnToggleFunction.Arn

  WebSocketURI:
    Description: "The WSS Protocol URI to connect to"
    Value:
      !Join [
        "",
        [
          "wss://",
          !Ref RGempadBackendApi,
          ".execute-api.",
          !Ref "AWS::Region",
          ".amazonaws.com/",
          !Ref "Stage",
        ],
      ]
