AWSTemplateFormatVersion: "2010-09-09"

# NOTE. Enables SAM shorthand for any AWS::Serverless::* resources
Transform: AWS::Serverless-2016-10-31
Description: >
  rgempad-backend

  SAM Template for rgempad-backend that has the DynamoDB table and Lambda
  functions needed to demonstrate the Websocket protocol on API Gateway.

Resources:

# State ######
  ConnectionsTable:
    # Holds the connection identifiers to set identifiers for each connected client
    # NOTE: By default SAM uses PAY_PER_REQUEST billing (on-demand) and enables SSE with an AWS-managed CMK.
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: !Sub "${AWS::StackName}-connections-table"
      PrimaryKey:
        Name: connectionId
        Type: String

  GemStateTable:
    # Holds the 16-bit gem state for each gemId
    # NOTE: By default SAM uses PAY_PER_REQUEST billing (on-demand) and enables SSE with an AWS-managed CMK.
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: !Sub "${AWS::StackName}-gem-state-table"
      PrimaryKey:
        Name: gemId
        Type: String

###############################################################
  RGempadHttpApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: RGempadHttpApi
      ProtocolType: HTTP
      # The route selection expression determines how the API Gateway selects the route to invoke based on the request.
      # In this case, we use the request path to determine the route.
      RouteSelectionExpression: "$request.method $request.path"

  #######
  RGempadHttpApiDeployment:
    Type: AWS::ApiGatewayV2::Deployment
    DependsOn:
      - GemPostRoute
    Properties:
      ApiId: !Ref RGempadHttpApi

  #######
  RGempadHttpApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      StageName: Prod
      Description:  RGempadHttpApi Prod Stage
      DeploymentId: !Ref RGempadHttpApiDeployment
      ApiId: !Ref RGempadHttpApi

  #######
  GemPostRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref RGempadHttpApi
      RouteKey: "POST /gem/{gemId}"
      AuthorizationType: NONE
      OperationName: GemPostRoute
      Target: !Join
        - "/"
        - - "integrations"
          - !Ref GemPostInteg

  #######
  GemPostInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref RGempadHttpApi
      Description: Gem Post Integration
      IntegrationType: AWS_PROXY
      IntegrationMethod: POST
      # Informs lambda payload and response object formats
      # seee: https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html
      PayloadFormatVersion: "2.0"
      IntegrationUri:
        Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GemPostFunction.Arn}/invocations

  #######
  GemPostFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: gempost/
      Handler: app.handler
      MemorySize: 256
      Runtime: nodejs20.x
      Environment:
        Variables:
          # Note: that cannot construct this envar for other functions because of circular dependencies
          # The API endpoint is constructed to ensure it works with a custom domain
          API_ENDPOINT: !Sub "https://${RGempadBackendApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}"
          CONNECTIONS_TABLE: !Ref ConnectionsTable
          GEM_STATE_TABLE: !Ref GemStateTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref GemStateTable
        - DynamoDBCrudPolicy:
            TableName: !Ref ConnectionsTable
        - Statement:
            - Effect: Allow
              Action:
                - "execute-api:ManageConnections"
              Resource:
                - !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RGempadBackendApi}/*"

  #######
  GemPostPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - RGempadHttpApi
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref GemPostFunction
      Principal: apigateway.amazonaws.com

###############################################################
  RGempadBackendApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: RGempadBackendApi
      ProtocolType: WEBSOCKET
      # The route selection expression determines how the API Gateway selects the route to invoke based on the request.
      # In this case, we use the request body to determine the route.
      # The expression "$request.body.type" means that the API Gateway will look for a "type" field in the JSON body of the request to determine which route to invoke.
      RouteSelectionExpression: "$request.body.type"

#######
  HelloRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref RGempadBackendApi
      # Note: that the route key is "hello" which means that the API Gateway will look for a "type" field in the JSON body
      # of the request with the value "hello" to invoke this route, per the RouteSelectionExpression.
      # WARNING: Changing the RouteKey will require forcing a new deployment.
      # Td. Learn how to force a new deployment without having to delete the stack
      RouteKey: hello
      AuthorizationType: NONE
      OperationName: HelloRoute
      Target: !Join
        - "/"
        - - "integrations"
          - !Ref HelloInteg
  HelloInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref RGempadBackendApi
      Description: Hello Integration
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${OnHelloFunction.Arn}/invocations

#######
  ToggleRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref RGempadBackendApi
      RouteKey: toggle
      AuthorizationType: NONE
      OperationName: ToggleRoute
      Target: !Join
        - "/"
        - - "integrations"
          - !Ref ToggleInteg
  ToggleInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref RGempadBackendApi
      Description: Toggle Integration
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${OnToggleFunction.Arn}/invocations

#######
  DisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref RGempadBackendApi
      # Note: that the route key is $disconnect which is a special route invoked when a client disconnects
      RouteKey: $disconnect
      AuthorizationType: NONE
      OperationName: DisconnectRoute
      Target: !Join
        - "/"
        - - "integrations"
          - !Ref DisconnectInteg
  DisconnectInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref RGempadBackendApi
      Description: Disconnect Integration
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${OnDisconnectFunction.Arn}/invocations

#######
  Deployment:
    Type: AWS::ApiGatewayV2::Deployment
    DependsOn:
      - HelloRoute
      - ToggleRoute
      - DisconnectRoute
    Properties:
      ApiId: !Ref RGempadBackendApi

#######
  Stage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      StageName: Prod
      Description: Prod Stage
      DeploymentId: !Ref Deployment
      ApiId: !Ref RGempadBackendApi

#######
# Heartbeat EventBridge rule
  HeartbeatScheduleRule:
    Type: AWS::Events::Rule
    Properties:
      # Lower heartbeat rate for testing, production should be 9 minutes
      Description: "Trigger heartbeat Lambda every 9 minutes"
      ScheduleExpression: rate(9 minutes)
      State: ENABLED
      Targets:
        - Arn: !GetAtt SchedHeartbeatFunction.Arn
          Id: HeartbeatFunctionTarget

  # Grant invocation permission from Events to Lambda
  HeartbeatPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref SchedHeartbeatFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt HeartbeatScheduleRule.Arn

##############
  OnHelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: onhello/
      Handler: app.handler
      MemorySize: 256
      Runtime: nodejs20.x
      Environment:
        Variables:
          CONNECTIONS_TABLE: !Ref ConnectionsTable        
          GEM_STATE_TABLE: !Ref GemStateTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ConnectionsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref GemStateTable
        - Statement:
          - Effect: Allow
            Action:
              - "execute-api:ManageConnections"
            Resource:
              - !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RGempadBackendApi}/*"

  OnHelloPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - RGempadBackendApi
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref OnHelloFunction
      Principal: apigateway.amazonaws.com

##############
  OnToggleFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ontoggle/
      Handler: app.handler
      MemorySize: 256
      Runtime: nodejs20.x
      Environment:
        Variables:
          CONNECTIONS_TABLE: !Ref ConnectionsTable        
          GEM_STATE_TABLE: !Ref GemStateTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ConnectionsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref GemStateTable
        - Statement:
            - Effect: Allow
              Action:
                - "execute-api:ManageConnections"
              Resource:
                - !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RGempadBackendApi}/*"

  OnTogglePermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - RGempadBackendApi
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref OnToggleFunction
      Principal: apigateway.amazonaws.com

##############
  OnDisconnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ondisconnect/
      Handler: app.handler
      MemorySize: 256
      Runtime: nodejs20.x
      Environment:
        Variables:
          CONNECTIONS_TABLE: !Ref ConnectionsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ConnectionsTable

  OnDisconnectPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - RGempadBackendApi
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref OnDisconnectFunction
      Principal: apigateway.amazonaws.com

##############
  SchedHeartbeatFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: schedhb/
      Handler: app.handler
      MemorySize: 256
      Runtime: nodejs20.x
      Environment:
        Variables:
          # Note: that cannot construct this envar for other functions because of circular dependencies
          # The API endpoint is constructed to ensure it works with a custom domain
          API_ENDPOINT: !Sub "https://${RGempadBackendApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}"
          CONNECTIONS_TABLE: !Ref ConnectionsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ConnectionsTable
        - Statement:
            - Effect: Allow
              Action:
                - "execute-api:ManageConnections"
              Resource:
                - !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RGempadBackendApi}/*"

  SchedHeartbeatFunctionPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - RGempadBackendApi
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref  SchedHeartbeatFunction
      Principal: apigateway.amazonaws.com

###############################################################
Outputs:
  ConnectionsTableArn:
    Description: "Connections table ARN"
    Value: !GetAtt ConnectionsTable.Arn

  GemStateTableArn:
    Description: "Gem State table ARN"
    Value: !GetAtt GemStateTable.Arn

  OnHelloFunctionArn:
    Description: "OnHello function ARN"
    Value: !GetAtt OnHelloFunction.Arn

  OnToggleFunctionArn:
    Description: "OnToggle function ARN"
    Value: !GetAtt OnToggleFunction.Arn

  SchedHeartbeatFunctionArn:
    Description:  "SchedHeartbeat function ARN"
    Value: !GetAtt  SchedHeartbeatFunction.Arn

  OnDisconnectFunctionArn:
    Description: "OnDisconnect function ARN"
    Value: !GetAtt OnDisconnectFunction.Arn

  WebSocketURI:
    Description: "The WSS Protocol URI to connect to"
    Value:
      !Join [
        "",
        [
          "wss://",
          !Ref RGempadBackendApi,
          ".execute-api.",
          !Ref "AWS::Region",
          ".amazonaws.com/",
          !Ref "Stage",
        ],
      ]

  HttpApiEndpoint:
    Description: "The HTTPS Protocol URI to connect to"
    Value:
      !Join [
        "",
        [
          "https://",
          !Ref RGempadHttpApi,
          ".execute-api.",
          !Ref "AWS::Region",
          ".amazonaws.com/",
          !Ref "RGempadHttpApiStage",
        ],
      ]