#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="${SCRIPT_DIR}/../.."
REGION="us-east-1"

# Source stamped environment (generated by configure.sh)
ENV_FILE="${ROOT_DIR}/.env"
if [[ ! -f "${ENV_FILE}" ]]; then
  echo "Error: ${ENV_FILE} not found. Run ./configure.sh <env> first." >&2
  exit 1
fi
source "${ENV_FILE}"

STACK_NAME="rgem-${RGEM_ENV}"
GEM_STATE_TABLE="${STACK_NAME}-gem-state-table"
CONNECTIONS_TABLE="${STACK_NAME}-connections-table"

echo "=== Clear DynamoDB Tables ==="
echo "  Environment       : ${RGEM_ENV}"
echo "  GemState table    : ${GEM_STATE_TABLE}"
echo "  Connections table : ${CONNECTIONS_TABLE}"
echo ""
echo "Active connections will be dropped; clients reconnect automatically."
echo ""
read -rp "This will delete all rows from both tables. Continue? [y/N] " confirm
if [[ "${confirm}" != "y" && "${confirm}" != "Y" ]]; then
  echo "Aborted."
  exit 0
fi

# Scan a table for all primary key values and delete each item.
clear_table() {
  local table="$1"
  local pk_attr="$2"

  echo "Scanning ${table}..."

  local keys
  keys=$(aws dynamodb scan \
    --table-name "${table}" \
    --region "${REGION}" \
    --projection-expression "#pk" \
    --expression-attribute-names "{\"#pk\": \"${pk_attr}\"}" \
    --output json \
    | python3 -c "
import sys, json
data = json.load(sys.stdin)
for item in data['Items']:
    print(list(item.values())[0]['S'])
")

  local count=0
  while IFS= read -r key; do
    [[ -z "${key}" ]] && continue
    aws dynamodb delete-item \
      --table-name "${table}" \
      --region "${REGION}" \
      --key "{\"${pk_attr}\": {\"S\": \"${key}\"}}" \
      > /dev/null
    (( count++ ))
  done <<< "${keys}"

  echo "Deleted ${count} item(s) from ${table}."
}

clear_table "${GEM_STATE_TABLE}" "gemId"
clear_table "${CONNECTIONS_TABLE}" "connectionId"

echo ""
echo "Done. Both tables are now empty."
