#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="${SCRIPT_DIR}/../.."

# Source stamped environment (generated by configure.sh)
ENV_FILE="${ROOT_DIR}/.env"
if [[ ! -f "${ENV_FILE}" ]]; then
  echo "Error: ${ENV_FILE} not found. Run ./configure.sh <env> first." >&2
  exit 1
fi
source "${ENV_FILE}"

echo "Deploying backend for '${RGEM_ENV}'..."

cd "${ROOT_DIR}"

# Note: `sam deploy` with `resolve_s3 = true` (set in `samconfig.toml`) handles packaging automatically.
# If you set up a CI/CD pipeline where you need to package once and deploy to multiple environments separately,
# reintroduce `sam package` as a standalone step with an explicit `--s3-bucket` and `--output-template-file`,
# then deploy the packaged template via `sam deploy --template-file <packaged.yaml> --config-env <env>`.
sam build && sam deploy --config-env "${RGEM_ENV}"
