#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="${SCRIPT_DIR}/../.."

# Source stamped environment (generated by configure.sh)
ENV_FILE="${ROOT_DIR}/.env"
if [[ ! -f "${ENV_FILE}" ]]; then
  echo "Error: ${ENV_FILE} not found. Run ./configure.sh <env> first." >&2
  exit 1
fi
source "${ENV_FILE}"

# Guard: landing page is prod-only
if [[ "${RGEM_ENV}" != "prod" ]]; then
  echo "Error: landing page is only deployed to prod (current env: '${RGEM_ENV}')." >&2
  exit 1
fi

echo "Deploying landing page for 'prod'..."

BUCKET="rgem-prod-landing-bucket"

aws s3 sync "${ROOT_DIR}/landing/" "s3://${BUCKET}/" --delete

# Get CloudFront distribution ID from CloudFormation output
DIST_ID=$(aws cloudformation describe-stacks \
  --stack-name "rgem-prod" \
  --query "Stacks[0].Outputs[?OutputKey=='LandingDistributionId'].OutputValue" \
  --output text)

aws cloudfront create-invalidation \
  --distribution-id "${DIST_ID}" \
  --paths "/*"
