#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="${SCRIPT_DIR}/../.."

# Source stamped environment (generated by configure.sh)
ENV_FILE="${ROOT_DIR}/.env"
if [[ ! -f "${ENV_FILE}" ]]; then
  echo "Error: ${ENV_FILE} not found. Run ./configure.sh <env> first." >&2
  exit 1
fi
source "${ENV_FILE}"

echo "Deploying app for '${RGEM_ENV}'..."

# Build SPA
pushd "${ROOT_DIR}/app"
npm install
VITE_API_BASE_URL="https://${RGEM_API_HOST}" \
VITE_WS_URL="wss://${RGEM_WS_HOST}" \
npm run build
popd

# Bucket name must match your SAM template and sam config
BUCKET="rgem-${RGEM_ENV}-app-bucket"

aws s3 sync "${ROOT_DIR}/app/dist/" "s3://${BUCKET}/" --delete

# Get CloudFront distribution ID from CloudFormation output
DIST_ID=$(aws cloudformation describe-stacks \
  --stack-name "rgem-${RGEM_ENV}" \
  --query "Stacks[0].Outputs[?OutputKey=='AppDistributionId'].OutputValue" \
  --output text)

aws cloudfront create-invalidation \
  --distribution-id "${DIST_ID}" \
  --paths "/*"
