#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="${SCRIPT_DIR}/../.."
REGION="us-east-1"

# Source stamped environment (generated by configure.sh)
ENV_FILE="${ROOT_DIR}/.env"
if [[ ! -f "${ENV_FILE}" ]]; then
  echo "Error: ${ENV_FILE} not found. Run ./configure.sh <env> first." >&2
  exit 1
fi
source "${ENV_FILE}"

STACK_NAME="rgem-${RGEM_ENV}"
BUCKET="rgem-${RGEM_ENV}-frontend-bucket"

echo "=== Force-delete CloudFormation stack ==="
echo "  Environment : ${RGEM_ENV}"
echo "  Stack       : ${STACK_NAME}"
echo "  Region      : ${REGION}"
echo ""
read -rp "This will permanently destroy all resources in this stack. Continue? [y/N] " confirm
if [[ "${confirm}" != "y" && "${confirm}" != "Y" ]]; then
  echo "Aborted."
  exit 0
fi

# Verify stack exists
if ! aws cloudformation describe-stacks \
  --stack-name "${STACK_NAME}" \
  --region "${REGION}" \
  > /dev/null 2>&1; then
  echo "Stack '${STACK_NAME}' does not exist. Nothing to delete."
  exit 0
fi

# Disable CloudFront distribution — CloudFormation cannot delete an enabled distribution.
# Fetch the distribution ID from CloudFormation outputs.
DIST_ID=$(aws cloudformation describe-stacks \
  --stack-name "${STACK_NAME}" \
  --region "${REGION}" \
  --query "Stacks[0].Outputs[?OutputKey=='FrontendDistributionId'].OutputValue" \
  --output text 2>/dev/null || true)

if [[ -n "${DIST_ID}" && "${DIST_ID}" != "None" ]]; then
  echo "Disabling CloudFront distribution ${DIST_ID}..."

  # Get the current distribution config and ETag
  DIST_CONFIG_JSON=$(aws cloudfront get-distribution-config \
    --id "${DIST_ID}" \
    --output json)

  ETAG=$(echo "${DIST_CONFIG_JSON}" | python3 -c "import sys,json; print(json.load(sys.stdin)['ETag'])")
  ENABLED=$(echo "${DIST_CONFIG_JSON}" | python3 -c "import sys,json; print(json.load(sys.stdin)['DistributionConfig']['Enabled'])")

  if [[ "${ENABLED}" == "True" ]]; then
    # Set Enabled to false and update the distribution
    UPDATED_CONFIG=$(echo "${DIST_CONFIG_JSON}" | python3 -c "
import sys, json
data = json.load(sys.stdin)
config = data['DistributionConfig']
config['Enabled'] = False
print(json.dumps(config))
")
    aws cloudfront update-distribution \
      --id "${DIST_ID}" \
      --if-match "${ETAG}" \
      --distribution-config "${UPDATED_CONFIG}" \
      > /dev/null

    echo "Waiting for CloudFront distribution to reach 'Deployed' state (this may take several minutes)..."
    aws cloudfront wait distribution-deployed --id "${DIST_ID}"
    echo "CloudFront distribution disabled."
  else
    echo "CloudFront distribution already disabled."
  fi
else
  echo "No CloudFront distribution found in stack outputs; skipping disable step."
fi

# Empty the frontend S3 bucket
echo "Emptying S3 bucket ${BUCKET}..."
aws s3 rm "s3://${BUCKET}" --recursive 2>/dev/null || echo "Bucket ${BUCKET} not found or already empty; continuing."

# Delete the CloudFormation stack
echo "Deleting stack ${STACK_NAME}..."
aws cloudformation delete-stack \
  --stack-name "${STACK_NAME}" \
  --region "${REGION}"

echo "Waiting for stack deletion to complete..."
aws cloudformation wait stack-delete-complete \
  --stack-name "${STACK_NAME}" \
  --region "${REGION}"

echo ""
echo "Stack '${STACK_NAME}' deleted successfully."
echo "You can now redeploy with deploy-backend.sh and deploy-frontend.sh."
