#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="${SCRIPT_DIR}/../.."
REGION="us-east-1"

# Source stamped environment (generated by configure.sh)
ENV_FILE="${ROOT_DIR}/.env"
if [[ ! -f "${ENV_FILE}" ]]; then
  echo "Error: ${ENV_FILE} not found. Run ./configure.sh <env> first." >&2
  exit 1
fi
source "${ENV_FILE}"

STACK_NAME="rgem-${RGEM_ENV}"
APP_BUCKET="rgem-${RGEM_ENV}-app-bucket"

echo "=== Force-delete CloudFormation stack ==="
echo "  Environment : ${RGEM_ENV}"
echo "  Stack       : ${STACK_NAME}"
echo "  Region      : ${REGION}"
echo ""
read -rp "This will permanently destroy all resources in this stack. Continue? [y/N] " confirm
if [[ "${confirm}" != "y" && "${confirm}" != "Y" ]]; then
  echo "Aborted."
  exit 0
fi

# Verify stack exists
if ! aws cloudformation describe-stacks \
  --stack-name "${STACK_NAME}" \
  --region "${REGION}" \
  > /dev/null 2>&1; then
  echo "Stack '${STACK_NAME}' does not exist. Nothing to delete."
  exit 0
fi

# Helper: disable a CloudFront distribution by ID.
# CloudFormation cannot delete an enabled distribution.
disable_distribution() {
  local dist_id="$1"

  if [[ -z "${dist_id}" || "${dist_id}" == "None" ]]; then
    echo "No distribution ID provided; skipping disable step."
    return
  fi

  echo "Disabling CloudFront distribution ${dist_id}..."

  DIST_CONFIG_JSON=$(aws cloudfront get-distribution-config \
    --id "${dist_id}" \
    --output json)

  ETAG=$(echo "${DIST_CONFIG_JSON}" | python3 -c "import sys,json; print(json.load(sys.stdin)['ETag'])")
  ENABLED=$(echo "${DIST_CONFIG_JSON}" | python3 -c "import sys,json; print(json.load(sys.stdin)['DistributionConfig']['Enabled'])")

  if [[ "${ENABLED}" == "True" ]]; then
    UPDATED_CONFIG=$(echo "${DIST_CONFIG_JSON}" | python3 -c "
import sys, json
data = json.load(sys.stdin)
config = data['DistributionConfig']
config['Enabled'] = False
print(json.dumps(config))
")
    aws cloudfront update-distribution \
      --id "${dist_id}" \
      --if-match "${ETAG}" \
      --distribution-config "${UPDATED_CONFIG}" \
      > /dev/null

    echo "Waiting for CloudFront distribution to reach 'Deployed' state (this may take several minutes)..."
    aws cloudfront wait distribution-deployed --id "${dist_id}"
    echo "CloudFront distribution ${dist_id} disabled."
  else
    echo "CloudFront distribution ${dist_id} already disabled."
  fi
}

# Disable the app CloudFront distribution
APP_DIST_ID=$(aws cloudformation describe-stacks \
  --stack-name "${STACK_NAME}" \
  --region "${REGION}" \
  --query "Stacks[0].Outputs[?OutputKey=='AppDistributionId'].OutputValue" \
  --output text 2>/dev/null || true)

disable_distribution "${APP_DIST_ID}"

# Empty the app S3 bucket
echo "Emptying S3 bucket ${APP_BUCKET}..."
aws s3 rm "s3://${APP_BUCKET}" --recursive 2>/dev/null || echo "Bucket ${APP_BUCKET} not found or already empty; continuing."

# Delete the CloudFormation stack
echo "Deleting stack ${STACK_NAME}..."
aws cloudformation delete-stack \
  --stack-name "${STACK_NAME}" \
  --region "${REGION}"

echo "Waiting for stack deletion to complete..."
aws cloudformation wait stack-delete-complete \
  --stack-name "${STACK_NAME}" \
  --region "${REGION}"

echo ""
echo "Stack '${STACK_NAME}' deleted successfully."
echo "You can now redeploy with deploy-backend.sh and deploy-app.sh."
